from flask import Flask, request, jsonify
from dotenv import load_dotenv
import os
import openai

app = Flask(__name__)

load_dotenv()

OPENAI_KEY = os.getenv('OPENAI_KEY')

openai.api_key = OPENAI_KEY

@app.route('/detect-ai', methods=['POST'])
def detect_ai():
    data = request.get_json()

    if 'text' not in data:
        return jsonify({'error': 'No text provided'}), 400

    text = data['text']

    num_requests = 1

    try:
        for _ in range(num_requests):
            response = openai.Completion.create(
                model="gpt-3.5-turbo-instruct",
                prompt=f"Respond with just a percentage indicating the likelihood that the following text was generated by AI: {text}",
                max_tokens=20,
                temperature=0.7
            )
            result = response.choices[0].text.strip()

        return jsonify({'AI Percentage Average': f"{result}"})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
